### ISSUE TITLE
Odd behavior on merged Orbit members

### ISSUE THREAD

**Issue by mattstratton** [orbit-love/orbit-browser-extension#13]
It seems for members that were merged (i.e., they had a member account that was created from Twitter and one from GH) that they don't work quite properly with this extension. When I click on "show X's profile on Orbit" it leads to a 404 as the path for that member isn't what the extension thinks it should be.

For example, the gh user `joeduffy` tries to go to `https://app.orbit.love/REDACTED/members/joeduffy` but since that account was merged, it returns a 404 and the actual URL for that user is `https://app.orbit.love/REDACTED/members/funcofjoe` because it was merged with that Twitter member.

**Comment by martyndavies** [comment]
Hey @mattstratton, good catch, we'll take a look at this.

**Comment by phacks** [comment]
Thanks for opening the issue @mattstratton!

I think the reason why it does not work is that a few pieces of code (including the link to the profile) do not account for merges (or manual slug updates for that matter):

https://github.com/orbit-love/orbit-browser-extension/blob/a8edf5590fc03efe56129e4b121b78ac3305de54/src/github/orbit-action.js#L319-L328

I think we have the member slug at that point (although we might need to pass it as an argument) and thus could use it in places where we use `githubUsername`.

**Comment by martyndavies** [comment]
Hey @mattstratton, thanks again for highlighting this. It's now been fixed and a new version of the extension has been deployed to Google. It's available now, and might automatically update if you restart your browser, but you can always force the update by heading to chrome://extensions/, then 'Details' on the Orbit extension, and hit 'Update'.
