### ISSUE TITLE
Feature Request: Support for GH Discussions

### ISSUE THREAD

**Issue by mattstratton** [orbit-love/orbit-browser-extension#16]
Minor thing that would be helpful - it would be great if this extension also showed Orbit info on members on posts/threads in GitHub Discussions (I know that Orbit doesn't integrate with Discussions yet, but being able to see the Orbit info that we do have would be great!)

**Comment by martyndavies** [comment]
Thanks for the suggestion @mattstratton. I'll take a look at implementing this.

**Comment by phacks** [comment]
Hey @mattstratton! I know it’s been a long time coming (and we apologize), but I wanted to let you know that the newest version of the extension now supports GitHub Discussions 🙌 Thanks for the suggestion.
The extension updates automatically on Chrome restarts and can be updated manually by visiting chrome://extensions
