### ISSUE TITLE
Github orgs with many repos prevent the extension from saving data

### ISSUE THREAD

**Issue by ryjones** [orbit-love/orbit-browser-extension#26]
Using latest Edge, etc.

I have about 300 github repos in my org. When I try to save my settings, this error pops up in the console, but the extension reports success:

<img width="503" alt="Screenshot_2022-08-03_at_8 04 11_AM" src="https://user-images.githubusercontent.com/466142/182649003-a9af7d6b-b62f-48ff-83d7-a033b8124859.png">

```
Uncaught (in promise) Error: QUOTA_BYTES_PER_ITEM quota exceeded
    at chrome-extension-async.js:46:1
(anonymous) @ chrome-extension-async.js:46
```

**Comment by phacks** [comment]
Thanks for opening an issue @ryjones! Indeed, from the [`chrome.storage` docs](https://developer.chrome.com/docs/extensions/reference/storage/#property-sync) it looks like items in the storage must not exceed 8Kb (around 8k chars apparently).

My intuition would be that we can add a while loop before the `storage.sync.set` call below, that trims down the string if its JSON representation exceeds the limit.

https://github.com/orbit-love/orbit-browser-extension/blob/0c186eb48099aa3c2b54e1204522671a1d1f9e97/src/options/options.js#L96-L101
