### ISSUE TITLE
Unexpected UI formatting on GitHub discussion 

### ISSUE THREAD

**Issue by alexlsalt** [orbit-love/orbit-browser-extension#68]
## Overview

I'd expect to see these buttons side by side, but I'm seeing them stacked vertically. The issue appears to be occurring on **GitHub Discussion** posts.

![CleanShot 2023-06-21 at 15 53 21@2x](https://github.com/orbit-love/orbit-browser-extension/assets/45923677/4b207724-27cb-43cf-8869-36642ade0932)

**Comment by phacks** [comment]
Thanks for reporting @alexlsalt! We’ll take a look 👍

**Comment by phacks** [comment]
Hey @alexlsalt! It’s possible you’re running an older version of the code (the internal beta build maybe?). Could you try and go to [chrome://extensions](chrome://extensions), remove Orbit, and re-add it [from the Chrome Webstore](https://chrome.google.com/webstore/detail/orbit/ibgahekkldapaohbpmpbckmeljidicmn/)?
Hopefully this should fix the issue!

**Comment by alexlsalt** [comment]
@phacks That was totally it, thanks!!

<img width="940" alt="CleanShot 2023-06-23 at 12 24 14@2x" src="https://github.com/orbit-love/orbit-browser-extension/assets/45923677/449b521d-417b-4761-9fa8-688ba1c0cf08">
